### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dev-mtshikomba** [geraldokandonga/votenamibia-api#1]
Not sure what is causing the error below but  whenever I do `$ npm run dev` OR `$ npm run start` it pops up and I can't do anything else. I am using Ubuntu 16.04. 

> (base) tangos@ubuntu:~/votenamibia$ npm run dev
> 
> > vote@1.0.0 dev
> > nodemon server.js
> 
> [nodemon] 2.0.6
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching path(s): *.*
> [nodemon] watching extensions: js,mjs,json
> [nodemon] starting `node server.js`
> UNCAUGHT EXCEPTION! Shutting down...
> TypeError Cannot read property 'replace' of undefined
> [nodemon] app crashed - waiting for file changes before starting...

Here is my npm and node version not sure if it has anything to do with this but i had to upgrade from an earlier:

> (base) tangos@ubuntu:~/votenamibia$ npm -v
> `7.0.14`
> (base) tangos@ubuntu:~/votenamibia$ node -v
> `v15.3.0`

**Comment by geraldokandonga** [comment]
Hi @dev-mtshikomba have you run `npm install` ? 

Also you need to have MongoDB Compass Community  installed locally on your machine and create a database with the name votenamibia, or you can still connect to mongoDB through your account if you have

To connect MongoDB remote bellow is the code
`DATABASE=mongodb+srv://<yourusername>:<PASSWORD>@cluster0-bev59.mongodb.net/votenamibia
?retryWrites=true&w=majority
DATABASE_PASSWORD=<PASSWORD>`

To Connect locally
`DATABASE_LOCAL=mongodb://localhost:27017/votenamibia`

That's  all

**Comment by geraldokandonga** [comment]
Create a config.env file and add the following 

`APP_NAME=VoteNamibia
NODE_ENV=development
PORT=3000

DATABASE_PASSWORD=<PASSWORD>
DATABASE_LOCAL=mongodb://localhost:27017/<dbname>

JWT_SECRET=never-<randomstring>
JWT_EXPIRES_IN=90d
JWT_COOKIE_EXPIRES_IN=90

EMAIL_USERNAME=mailtrapusername
EMAIL_PASSWORD=mailtrappassword
EMAIL_HOST=smtp.mailtrap.io
EMAIL_PORT=25`

You need the above config.env in order to run it locally

**Comment by dev-mtshikomba** [comment]
I've run `npm install`, I should create the `config.env` file in the root directory right? See Image below...

![Screenshot from 2020-11-26 21-43-21](https://user-images.githubusercontent.com/10866232/100415264-9ddcf880-3030-11eb-9ebd-68daa6d9d066.png)

**Comment by dev-mtshikomba** [comment]
I installed MongoDB  locally in a docker image running at port 8081. See Image below.

![Screenshot from 2020-11-26 21-47-09](https://user-images.githubusercontent.com/10866232/100415429-f8765480-3030-11eb-89a5-84a3960f27c3.png)

**Comment by geraldokandonga** [comment]
Thats mongodb connection error, but can you connect to it with other apps that you may have worked on, if you are already connected to it through another app than I think you have to use the same method

And again don't forget to setup your mailing configuration, you need to do sign in if you want to add some testing data to the database

But the setup seems to be fine, thats all you need to run it locally

**Comment by geraldokandonga** [comment]
Also you need to expose your port to mongo by running mongo --port 8081 in your terminal

**Comment by dev-mtshikomba** [comment]
Perfect this worked. I've added a Docker Image for MongoDB and Mongo Express to the project.  I'll submit a pull request shortly.
![Screenshot from 2020-11-26 21-43-21](https://user-images.githubusercontent.com/10866232/100523294-4b9cf400-3164-11eb-93dc-b6f8b80f44c7.png)

**Comment by dev-mtshikomba** [comment]
But I used the default port instead, just for consistency.

**Comment by geraldokandonga** [comment]
Great is it working now?
